[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.build]
cmds = ["cd eatsandthinks-backend && ./mvnw clean package -DskipTests"]

[start]
cmd = "cd eatsandthinks-backend && java -jar target/*.jar"

