[build]
builder = "nixpacks"
buildCommand = "cd eatsandthinks-backend && ./mvnw clean package -DskipTests"

[deploy]
startCommand = "cd eatsandthinks-backend && java -jar target/*.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

